#include "main.h"




/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:02:27
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI4)
 *
 * Arguments    : double F
 *                double Tp
 *                double phi1
 *                double phi4
 *                double T[2]
 * Return Type  : void
 */
 
 //matlab生成的vmc解算函数，还得改
void leg_conv(double F, double Tp, double phi1, double phi4, double T[2])//输入目标F和Tp，和当前的phi1和phi4，得出所需的两个实际的T
{
  double t112;
  double t114;
  double t118;
  double t130;
  double t133;
  double t141;
  double t16;
  double t18;
  double t33;
  double t34;
  double t35;
  double t36;
  double t4;
  double t49;
  double t5;
  double t50;
  double t57;
  double t58;
  double t59;
  double t6;
  double t60;
  double t61;
  double t62;
  double t7;
  double t91;
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-04-13 12:53:29 */
  t4 = cos(phi1);
  t5 = cos(phi4);
  t6 = sin(phi1);
  t7 = sin(phi4);
  t16 = t4 / 20.0;
  t18 = t6 / 20.0;
  t33 = t4 * 0.0105;
  t34 = t5 * 0.0105;
  t35 = t6 * 0.0105;
  t36 = t7 * 0.0105;
  t49 = t16 - t5 / 20.0;
  t50 = t18 - t7 / 20.0;
  t57 = t33 - t34;
  t58 = t35 - t36;
  t59 = t6 * t49 / 10.0;
  t60 = t7 * t49 / 10.0;
  t61 = t4 * t50 / 10.0;
  t62 = t5 * t50 / 10.0;
  t91 = t49 * t49 + t50 * t50;
  t49 = 1.0 / ((t34 - t33) + t91);
  t50 = t49 * t49;
  t112 = sqrt((t57 * t57 + t58 * t58) - t91 * t91);
  t114 = 1.0 / t112;
  t118 = (t36 - t35) + t112;
  t130 = atan(t49 * t118) * 2.0;
  t133 = cos(t130);
  t130 = sin(t130);
  t141 = 1.0 / (t50 * (t118 * t118) + 1.0);
  t112 = ((t35 + t61) - t59) * t50 * t118 +
         t49 * (t33 - t114 *
                          ((t4 * t58 * 0.021 - t6 * t57 * 0.021) +
                           t91 * (t59 - t61) * 2.0) /
                          2.0);
  t6 = ((t36 + t62) - t60) * t50 * t118 +
       t49 * (t34 - t114 *
                        ((t5 * t58 * 0.021 - t7 * t57 * 0.021) +
                         t91 * (t60 - t62) * 2.0) /
                        2.0);
  t33 = t16 + t133 * 0.105;
  t35 = t18 + t130 * 0.105;
  t114 = t33 * t33;
  t59 = 1.0 / t33;
  t118 = t35 * t35 + t114;
  t4 = t133 * t141;
  t91 = t16 - t4 * t112 * 0.21;
  t130 *= t141;
  t50 = t18 - t130 * t112 * 0.21;
  t112 = F * (1.0 / sqrt(t118));
  t49 = Tp * t114 * (1.0 / t118);
  t118 = t35 * (1.0 / t114);
  T[0] = t112 * (t35 * t91 * 2.0 - t33 * t50 * 2.0) / 2.0 +
         t49 * (t59 * t91 + t118 * t50);
  T[1] = t112 * (t4 * t35 * t6 * 0.42 - t130 * t33 * t6 * 0.42) / 2.0 -
         t49 * (t59 * (0.0 - t4 * t6 * 0.21) - t118 * (t130 * t6 * 0.21));
}




/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:08:56
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : double phi1
 *                double phi4
 *                double pos[2]
 * Return Type  : void
 */
void leg_pos(double phi1, double phi4, float* pos1,float* pos2)//输入phi1和phi4，得出phi0和l0
{
  double t12;
  double t13;
  double t14;
  double t15;
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t8;
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-04-13 12:53:27 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 / 20.0;
  t8 = t4 / 20.0;
  t12 = t2 * 0.0105;
  t13 = t3 * 0.0105;
  t14 = t4 * 0.0105;
  t15 = t5 * 0.0105;
  t4 = t6 - t3 / 20.0;
  t2 = t8 - t5 / 20.0;
  t3 = t12 - t13;
  t5 = t14 - t15;
  t2 = t4 * t4 + t2 * t2;
  t2 = atan(1.0 / ((t13 - t12) + t2) *
            ((t15 - t14) + sqrt((t3 * t3 + t5 * t5) - t2 * t2))) *
       2.0;
  t4 = t8 + sin(t2) * 0.105;
  t2 = t6 + cos(t2) * 0.105;
  *pos1 = sqrt(t4 * t4 + t2 * t2);
  *pos2 = atan2(t4, t2);
}


/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-19 15:34:42
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : double dphi1
 *                double dphi4
 *                double phi1
 *                double phi4
 *                double spd[2]
 * Return Type  : void
 */
void leg_spd(double dphi1, double dphi4, double phi1, double phi4,
             Leg_State_t* Leg_State)
{
    Leg_State->dphi1 = dphi1;
    Leg_State->phi1 = phi1;
    Leg_State->dphi4 =  dphi4;
    Leg_State->phi4 = phi4;
    double t10;
    double t12;
    double t2;
    double t21;
    double t22;
    double t23;
    double t24;
    double t29;
    double t3;
    double t30;
    double t33;
    double t34;
    double t35;
    double t36;
    double t37;
    double t38;
    double t4;
    double t5;
    double t51;
    double t59;
    double t60;
    double t64;
    double t66;
    double t73;
    /*     This function was generated by the Symbolic Math Toolbox version 25.1.
    */
    /*     2026-04-13 12:53:28 */
    t2 = cos(phi1);
    t3 = cos(phi4);
    t4 = sin(phi1);
    t5 = sin(phi4);
    t10 = t2 / 20.0;
    t12 = t4 / 20.0;
    t21 = t2 * 0.0105;
    t22 = t3 * 0.0105;
    t23 = t4 * 0.0105;
    t24 = t5 * 0.0105;
    t29 = t10 - t3 / 20.0;
    t30 = t12 - t5 / 20.0;
    t33 = t21 - t22;
    t34 = t23 - t24;
    t35 = t4 * t29 / 10.0;
    t36 = t5 * t29 / 10.0;
    t37 = t2 * t30 / 10.0;
    t38 = t3 * t30 / 10.0;
    t51 = t29 * t29 + t30 * t30;
    t59 = 1.0 / ((t22 - t21) + t51);
    t60 = t59 * t59;
    t64 = sqrt((t33 * t33 + t34 * t34) - t51 * t51);
    t29 = 1.0 / t64;
    t66 = (t24 - t23) + t64;
    t73 = atan(t59 * t66) * 2.0;
    t30 = cos(t73);
    t64 = sin(t73);
    t73 = 1.0 / (t60 * (t66 * t66) + 1.0);
    t23 = ((t23 + t37) - t35) * t60 * t66 +
        t59 * (t21 - t29 *
                         ((t2 * t34 * 0.021 - t4 * t33 * 0.021) +
                          t51 * (t35 - t37) * 2.0) /
                         2.0);
    t29 = ((t24 + t38) - t36) * t60 * t66 +
        t59 * (t22 - t29 *
                         ((t3 * t34 * 0.021 - t5 * t33 * 0.021) +
                          t51 * (t36 - t38) * 2.0) /
                         2.0);
    t2 = t10 + t30 * 0.105;
    t4 = t12 + t64 * 0.105;
    t66 = t30 * t73;
    t21 = t66 * t29;
    t64 *= t73;
    t51 = t64 * t29;
    t59 = t2 * t2;
    t60 = 1.0 / t2;
    t30 = t4 * t4 + t59;
    t29 = 1.0 / sqrt(t30);
    t73 = 1.0 / t30;
    t66 = t10 - t66 * t23 * 0.21;
    t30 = t12 - t64 * t23 * 0.21;
    Leg_State->dl0 = dphi4 * t29 * (t4 * t21 * 0.42 - t2 * t51 * 0.42) / 2.0 +
           dphi1 * t29 * (t4 * t66 * 2.0 - t2 * t30 * 2.0) / 2.0;
    t29 = t4 * (1.0 / t59);
    Leg_State->dphi0 = dphi1 * t59 * t73 * (t60 * t66 + t29 * t30) -
           dphi4 * t59 * t73 * (t60 * (0.0 - t21 * 0.21) - t29 * (t51 * 0.21));
}


/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])//后续double全改float
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-04-18 19:12:20 */
  t2 = L0 * L0;
  t3 = L0 * L0 * L0;
  K[0] = ((L0 * -5.1269913802949176 - t2 * 39.913888671630211) +
          t3 * 78.604478045680878) +
         0.02480998544590942;
  K[1] = ((L0 * 0.01641856041106354 + t2 * 0.061259181635613107) -
          t3 * 0.3621574460649537) -
         0.0020128854503085312;
  K[2] = ((L0 * -0.71381840211773706 - t2 * 7.7528646574520792) +
          t3 * 9.9144642079539054) +
         0.0063399588222037059;
  K[3] = ((L0 * 0.0025984670103667931 - t2 * 0.0053304800937654254) +
          t3 * 0.0080964598354374313) -
         1.809641608041399E-5;
  K[4] = ((L0 * -2.5389325509084988 - t2 * 13.91236665677687) +
          t3 * 39.0028358950772) +
         0.027201567827498111;
  K[5] = ((L0 * -0.032202579751853623 + t2 * 0.21739994263248469) -
          t3 * 0.56548413901368266) +
         0.0039767820350209209;
  K[6] = ((L0 * -2.3301449660897249 - t2 * 10.921421632281181) +
          t3 * 27.93115238852846) +
         0.015813294040514989;
  K[7] = ((L0 * 0.0087845086030684787 - t2 * 0.048006614127390462) +
          t3 * 0.1089191999323019) +
         0.00038415403553898321;
  K[8] = ((L0 * -20.100843409125449 + t2 * 128.61659339363291) -
          t3 * 322.886169845551) +
         1.6391376703906251;
  K[9] = ((L0 * 0.21296545583181989 - t2 * 1.616724329662024) +
          t3 * 4.40539173188267) +
         1.9640865609754921;
  K[10] = ((L0 * -0.70706961151100467 + t2 * 4.5913168769262391) -
           t3 * 11.60473605982506) +
          0.060216562152959383;
  K[11] = ((L0 * 0.003493240215959253 - t2 * 0.026255872163845079) +
           t3 * 0.071272683966722719) +
          0.072190949184177247;
}

