#include "main.h"

/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:02:27
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])//输入VMC所需的F Tp 和实际的phi1和phi4，得出所需电机力矩T
{
  float t110;
  float t112;
  float t118;
  float t134;
  float t141;
  float t16;
  float t18;
  float t19;
  float t20;
  float t22;
  float t23;
  float t4;
  float t49;
  float t5;
  float t50;
  float t51;
  float t52;
  float t6;
  float t63;
  float t64;
  float t67;
  float t68;
  float t7;
  float t91;
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-04-21 19:12:59 */
  t4 = cos(phi1);
  t5 = cos(phi4);
  t6 = sin(phi1);
  t7 = sin(phi4);
  t16 = t4 * 0.135;
  t18 = t4 * 0.0675;
  t19 = t5 * 0.0675;
  t20 = t6 * 0.135;
  t22 = t6 * 0.0675;
  t23 = t7 * 0.0675;
  t49 = t16 - t5 * 0.135;
  t50 = t18 - t19;
  t51 = t20 - t7 * 0.135;
  t52 = t22 - t23;
  t63 = t6 * t49 * 0.27;
  t64 = t7 * t49 * 0.27;
  t67 = t4 * t51 * 0.27;
  t68 = t5 * t51 * 0.27;
  t91 = t49 * t49 + t51 * t51;
  t49 = 1.0 / ((t19 - t18) + t91);
  t51 = t49 * t49;
  t110 = sqrt((t50 * t50 + t52 * t52) - t91 * t91);
  t112 = 1.0 / t110;
  t118 = (t23 - t22) + t110;
  t4 = atan(t49 * t118) * 2.0;
  t110 = cos(t4);
  t134 = sin(t4);
  t141 = 1.0 / (t51 * (t118 * t118) + 1.0);
  t63 = t51 * ((t22 + t67) - t63) * t118 +
        t49 * (t18 -
               t112 *
                   ((t16 * t52 + t6 * t50 * -0.135) + t91 * (t63 - t67) * 2.0) /
                   2.0);
  t67 = t51 * ((t23 + t68) - t64) * t118 +
        t49 * (t19 - t112 *
                         ((t7 * t50 * -0.135 + t91 * (t64 - t68) * 2.0) +
                          t5 * t52 * 0.135) /
                         2.0);
  t6 = t16 + t110 / 4.0;
  t18 = t20 + t134 / 4.0;
  t4 = t6 * t6;
  t22 = 1.0 / t6;
  t118 = t18 * t18 + t4;
  t112 = t110 * t141;
  t91 = t16 - t112 * t63 / 2.0;
  t110 = t134 * t141;
  t49 = t20 - t110 * t63 / 2.0;
  t51 = F * (1.0 / sqrt(t118));
  t118 = Tp * t4 * (1.0 / t118);
  t4 = t18 * (1.0 / t4);
  T[0] = t51 * (t18 * t91 * 2.0 - t6 * t49 * 2.0) / 2.0 +
         t118 * (t22 * t91 + t4 * t49);
  T[1] = t51 * (t112 * t18 * t67 - t110 * t6 * t67) / 2.0 -
         t118 * (t22 * (0.0 - t112 * t67 / 2.0) - t4 * (t110 * t67 / 2.0));
}



/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:08:56
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void leg_pos(float phi1, float phi4, float* pos1,float* pos2)//输入phi1和phi4，得出phi0和l0
{
  float a;
  float t10;
  float t12;
  float t13;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;
  float t9;
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-04-21 19:12:58 */
  t2 = cos(phi1);
  t3 = cos(phi4);
  t4 = sin(phi1);
  t5 = sin(phi4);
  t6 = t2 * 0.135;
  t8 = t2 * 0.0675;
  t9 = t3 * 0.0675;
  t10 = t4 * 0.135;
  t12 = t4 * 0.0675;
  t13 = t5 * 0.0675;
  t4 = t6 - t3 * 0.135;
  a = t8 - t9;
  t2 = t10 - t5 * 0.135;
  t3 = t12 - t13;
  t2 = t4 * t4 + t2 * t2;
  t2 = atan(1.0 / ((t9 - t8) + t2) *
            ((t13 - t12) + sqrt((a * a + t3 * t3) - t2 * t2))) *
       2.0;
  t4 = t10 + sin(t2) / 4.0;
  t2 = t6 + cos(t2) / 4.0;
  *pos1 = sqrt(t4 * t4 + t2 * t2);
  *pos2 = atan2(t4, t2);
}


/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-19 15:34:42
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : float dphi1
 *                float dphi4
 *                float phi1
 *                float phi4
 *                float spd[2]
 * Return Type  : void
 */
void leg_spd(float dphi1, float dphi4, float phi1, float phi4, Leg_State_t* Leg_State)//输入dphi1 dphi4 phi1 phi4 得出dl0和dphi0
{
    Leg_State->dphi1 = dphi1;
    Leg_State->phi1 = phi1;
    Leg_State->dphi4 =  dphi4;
    Leg_State->phi4 = phi4;
    float t10;
    float t12;
    float t13;
    float t14;
    float t16;
    float t17;
    float t2;
    float t29;
    float t3;
    float t30;
    float t31;
    float t32;
    float t37;
    float t38;
    float t4;
    float t41;
    float t42;
    float t5;
    float t51;
    float t57;
    float t58;
    float t63;
    float t66;
    float t81;
    /*     This function was generated by the Symbolic Math Toolbox version 25.1.
    */
    /*     2026-04-21 19:12:59 */
    t2 = cos(phi1);
    t3 = cos(phi4);
    t4 = sin(phi1);
    t5 = sin(phi4);
    t10 = t2 * 0.135;
    t12 = t2 * 0.0675;
    t13 = t3 * 0.0675;
    t14 = t4 * 0.135;
    t16 = t4 * 0.0675;
    t17 = t5 * 0.0675;
    t29 = t10 - t3 * 0.135;
    t30 = t12 - t13;
    t31 = t14 - t5 * 0.135;
    t32 = t16 - t17;
    t37 = t4 * t29 * 0.27;
    t38 = t5 * t29 * 0.27;
    t41 = t2 * t31 * 0.27;
    t42 = t3 * t31 * 0.27;
    t51 = t29 * t29 + t31 * t31;
    t57 = 1.0 / ((t13 - t12) + t51);
    t58 = t57 * t57;
    t2 = sqrt((t30 * t30 + t32 * t32) - t51 * t51);
    t63 = 1.0 / t2;
    t66 = (t17 - t16) + t2;
    t2 = atan(t57 * t66) * 2.0;
    t29 = cos(t2);
    t31 = sin(t2);
    t81 = 1.0 / (t58 * (t66 * t66) + 1.0);
    t16 =
      t58 * ((t16 + t41) - t37) * t66 +
      t57 * (t12 -
             t63 * ((t10 * t32 + t4 * t30 * -0.135) + t51 * (t37 - t41) * 2.0) /
                 2.0);
    t2 = t58 * ((t17 + t42) - t38) * t66 +
       t57 * (t13 - t63 *
                        ((t5 * t30 * -0.135 + t51 * (t38 - t42) * 2.0) +
                         t3 * t32 * 0.135) /
                        2.0);
    t41 = t10 + t29 / 4.0;
    t4 = t14 + t31 / 4.0;
    t51 = t29 * t81;
    t12 = t51 * t2;
    t31 *= t81;
    t57 = t31 * t2;
    t58 = t41 * t41;
    t63 = 1.0 / t41;
    t29 = t4 * t4 + t58;
    t2 = 1.0 / sqrt(t29);
    t66 = 1.0 / t29;
    t51 = t10 - t51 * t16 / 2.0;
    t29 = t14 - t31 * t16 / 2.0;
    Leg_State->dl0 = dphi4 * t2 * (t4 * t12 - t41 * t57) / 2.0 +
           dphi1 * t2 * (t4 * t51 * 2.0 - t41 * t29 * 2.0) / 2.0;
    t2 = t4 * (1.0 / t58);
    Leg_State->dphi0 = dphi1 * t58 * t66 * (t63 * t51 + t2 * t29) -
           dphi4 * t58 * t66 * (t63 * (0.0 - t12 / 2.0) - t2 * (t57 / 2.0));
}



/*
 * File trailer for leg_spd.c
 *
 * [EOF]
 */
/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
static float rt_powd_snf(float u0, float u1)
{
  float y;
  if (isnan(u0) || isnan(u1)) {
    y = NAN;
  } else {
    float d;
    y = fabs(u0);
    d = fabs(u1);
    if (isinf(u1)) {
      if (y == 1.0) {
        y = 1.0;
      } else if (y > 1.0) {
        if (u1 > 0.0) {
          y = INFINITY;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = INFINITY;
      }
    } else if (d == 0.0) {
      y = 1.0;
    } else if (d == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = NAN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void lqr_k(float L0, float K[12])//根据腿长得出LQR增益K
{
    float t2;
    float t3;
    /*     This function was generated by the Symbolic Math Toolbox version 25.1.
    */
    /*     2026-04-21 19:40:05 */
    t2 = L0 * L0;
    t3 = rt_powd_snf(L0, 3.0);
    K[0] = ((L0 * -193.611100445528 + t2 * 316.65559213225282) -
          t3 * 59.49627495055018) -
         3.933265601845584;
    K[1] = ((L0 * 36.213833642333917 - t2 * 126.5697098172855) +
          t3 * 21.8005940615697) +
         1.977243564461785;
    K[2] = ((L0 * -3.853866340575975 - t2 * 118.3279952903855) +
          t3 * 358.83072074817562) -
         0.80318085554946117;
    K[3] = ((L0 * -0.3972942026353794 + t2 * 29.33329175767) -
          t3 * 124.115072238369) +
         0.60104776257114;
    K[4] = ((L0 * -13.4706569384722 - t2 * 208.8269412224229) +
          t3 * 881.31342381849629) -
         1.841615277532169;
    K[5] = ((L0 * -0.4913275846376301 + t2 * 14.91752182501601) -
          t3 * 132.78555083062739) +
         2.208719107624876;
    K[6] = ((L0 * 1.620416883576945 - t2 * 309.13545907488788) +
          t3 * 1130.1619166117109) -
         2.652803579009706;
    K[7] = ((L0 * -10.22658318966298 + t2 * 99.375463779147424) -
          t3 * 370.8508537506404) +
         2.401681090419983;
    K[8] = ((L0 * -154.31288097758059 + t2 * 700.546953989207) -
          t3 * 1442.48454909) +
         21.535389298901769;
    K[9] = ((L0 * 109.4643693970168 - t2 * 673.787053836228) +
          t3 * 1619.6513976044689) +
         22.131012807980628;
    K[10] = ((L0 * -28.126490121238731 + t2 * 161.8350939126544) -
           t3 * 398.5072443792169) +
          3.3645215820998771;
    K[11] = ((L0 * 10.44495066221395 - t2 * 65.589932311367434) +
           t3 * 165.4655509010318) +
          2.9335570857411759;
}

void VMC_Data_Get(float dphi1, float dphi4, float phi1, float phi4, Leg_State_t* Leg_State)//整合求速度和求位置的两个函数
{
    leg_pos(phi1,phi4,&Leg_State->phi0,&Leg_State->l0);
    leg_spd(dphi1,dphi4,phi1,phi4,Leg_State);
}
