#include "main.h"

/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:02:27
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t110;
  float t112;
  float t118;
  float t130;
  float t133;
  float t141;
  float t16;
  float t18;
  float t21;
  float t22;
  float t24;
  float t25;
  float t4;
  float t49;
  float t5;
  float t50;
  float t55;
  float t56;
  float t6;
  float t63;
  float t64;
  float t65;
  float t66;
  float t7;
  float t91;
  /* LEG_CONV */
  /*     T = LEG_CONV(F,Tp,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:22 */
  t4 = cosf(phi1);
  t5 = cosf(phi4);
  t6 = sinf(phi1);
  t7 = sinf(phi4);
  t16 = t4 * 0.21F;
  t18 = t6 * 0.21F;
  t21 = t4 * 0.1008F;
  t22 = t5 * 0.1008F;
  t24 = t6 * 0.1008F;
  t25 = t7 * 0.1008F;
  t49 = t16 - t5 * 0.21F;
  t50 = t18 - t7 * 0.21F;
  t55 = t21 - t22;
  t56 = t24 - t25;
  t63 = t6 * t49 * 0.42F;
  t64 = t7 * t49 * 0.42F;
  t65 = t4 * t50 * 0.42F;
  t66 = t5 * t50 * 0.42F;
  t91 = t49 * t49 + t50 * t50;
  t49 = 1.0F / ((t22 - t21) + t91);
  t50 = t49 * t49;
  t110 = sqrtf((t55 * t55 + t56 * t56) - t91 * t91);
  t112 = 1.0F / t110;
  t118 = (t25 - t24) + t110;
  t130 = atanf(t49 * t118) * 2.0F;
  t133 = cosf(t130);
  t130 = sinf(t130);
  t141 = 1.0F / (t50 * (t118 * t118) + 1.0F);
  t110 = ((t24 + t65) - t63) * t50 * t118 +
         t49 * (t21 - t112 *
                          ((t4 * t56 * 0.2016F - t6 * t55 * 0.2016F) +
                           t91 * (t63 - t65) * 2.0F) /
                          2.0F);
  t6 = ((t25 + t66) - t64) * t50 * t118 +
       t49 * (t22 - t112 *
                        ((t5 * t56 * 0.2016F - t7 * t55 * 0.2016F) +
                         t91 * (t64 - t66) * 2.0F) /
                        2.0F);
  t21 = t16 + t133 * 0.24F;
  t24 = t18 + t130 * 0.24F;
  t112 = t21 * t21;
  t63 = 1.0F / t21;
  t118 = t24 * t24 + t112;
  t4 = t133 * t141;
  t91 = t16 - t4 * t110 * 0.48F;
  t130 *= t141;
  t50 = t18 - t130 * t110 * 0.48F;
  t110 = F * (1.0F / sqrtf(t118));
  t49 = Tp * t112 * (1.0F / t118);
  t118 = t24 * (1.0F / t112);
  T[0] = t110 * (t24 * t91 * 2.0F - t21 * t50 * 2.0F) / 2.0F +
         t49 * (t63 * t91 + t118 * t50);
  T[1] = t110 * (t4 * t24 * t6 * 0.96F - t130 * t21 * t6 * 0.96F) / 2.0F -
         t49 * (t63 * (0.0F - t4 * t6 * 0.48F) - t118 * (t130 * t6 * 0.48F));
}


/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:08:56
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void leg_pos(float phi1, float phi4, float pos[2])
{
  float t11;
  float t12;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;
  /* LEG_POS */
  /*     POS = LEG_POS(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:19 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t6 = t2 * 0.21F;
  t8 = t4 * 0.21F;
  t11 = t2 * 0.1008F;
  t12 = t3 * 0.1008F;
  t14 = t4 * 0.1008F;
  t15 = t5 * 0.1008F;
  t4 = t6 - t3 * 0.21F;
  t2 = t8 - t5 * 0.21F;
  t3 = t11 - t12;
  t5 = t14 - t15;
  t2 = t4 * t4 + t2 * t2;
  t2 = atanf(1.0F / ((t12 - t11) + t2) *
             ((t15 - t14) + sqrtf((t3 * t3 + t5 * t5) - t2 * t2))) *
       2.0F;
  t4 = t8 + sinf(t2) * 0.24F;
  t2 = t6 + cosf(t2) * 0.24F;
  pos[0] = sqrtf(t4 * t4 + t2 * t2);
  pos[1] = atan2f(t4, t2);
}



/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-19 15:34:42
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : float dphi1
 *                float dphi4
 *                float phi1
 *                float phi4
 *                float spd[2]
 * Return Type  : void
 */
void leg_spd(float dphi1, float dphi4, float phi1, float phi4, float spd[2])
{
  float t10;
  float t12;
  float t15;
  float t16;
  float t18;
  float t19;
  float t2;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t37;
  float t38;
  float t39;
  float t4;
  float t40;
  float t5;
  float t51;
  float t59;
  float t60;
  float t62;
  float t66;
  float t73;
  /* LEG_SPD */
  /*     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:21 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10 = t2 * 0.21F;
  t12 = t4 * 0.21F;
  t15 = t2 * 0.1008F;
  t16 = t3 * 0.1008F;
  t18 = t4 * 0.1008F;
  t19 = t5 * 0.1008F;
  t29 = t10 - t3 * 0.21F;
  t30 = t12 - t5 * 0.21F;
  t33 = t15 - t16;
  t34 = t18 - t19;
  t37 = t4 * t29 * 0.42F;
  t38 = t5 * t29 * 0.42F;
  t39 = t2 * t30 * 0.42F;
  t40 = t3 * t30 * 0.42F;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0F / ((t16 - t15) + t51);
  t60 = t59 * t59;
  t62 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t29 = 1.0F / t62;
  t66 = (t19 - t18) + t62;
  t73 = atanf(t59 * t66) * 2.0F;
  t30 = cosf(t73);
  t62 = sinf(t73);
  t73 = 1.0F / (t60 * (t66 * t66) + 1.0F);
  t18 = ((t18 + t39) - t37) * t60 * t66 +
        t59 * (t15 - t29 *
                         ((t2 * t34 * 0.2016F - t4 * t33 * 0.2016F) +
                          t51 * (t37 - t39) * 2.0F) /
                         2.0F);
  t29 = ((t19 + t40) - t38) * t60 * t66 +
        t59 * (t16 - t29 *
                         ((t3 * t34 * 0.2016F - t5 * t33 * 0.2016F) +
                          t51 * (t38 - t40) * 2.0F) /
                         2.0F);
  t2 = t10 + t30 * 0.24F;
  t4 = t12 + t62 * 0.24F;
  t66 = t30 * t73;
  t15 = t66 * t29;
  t62 *= t73;
  t51 = t62 * t29;
  t59 = t2 * t2;
  t60 = 1.0F / t2;
  t30 = t4 * t4 + t59;
  t29 = 1.0F / sqrtf(t30);
  t73 = 1.0F / t30;
  t66 = t10 - t66 * t18 * 0.48F;
  t30 = t12 - t62 * t18 * 0.48F;
  spd[0] = dphi4 * t29 * (t4 * t15 * 0.96F - t2 * t51 * 0.96F) / 2.0F +
           dphi1 * t29 * (t4 * t66 * 2.0F - t2 * t30 * 2.0F) / 2.0F;
  t29 = t4 * (1.0F / t59);
  spd[1] =
      dphi1 * t59 * t73 * (t60 * t66 + t29 * t30) -
      dphi4 * t59 * t73 * (t60 * (0.0F - t15 * 0.48F) - t29 * (t51 * 0.48F));
}


/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
void lqr_k(float L0, float K[12])//根据腿长得出LQR增益K
{
    float t2;
    float t3;
    /*     This function was generated by the Symbolic Math Toolbox version 25.1.
    */
    /*     2026-04-21 19:40:05 */
    t2 = L0 * L0;
    t3 = L0 * L0 * L0;
    K[0] = ((L0 * -102.7925908669374 - t2 * 213.03921376319349) +
          t3 * 832.2190168170664) -
         2.4815149341763592;
  K[1] = ((L0 * 1005.574338875969 - t2 * 1493.858190318075) -
          t3 * 8378.6026306558324) +
         50.156072514025858;
  K[2] = ((L0 * 0.22054841902621819 - t2 * 51.993783091702348) +
          t3 * 91.624833442818073) -
         0.19412005713278321;
  K[3] = ((L0 * 42.8437758097276 + t2 * 175.736184440077) -
          t3 * 1058.0099783368489) +
         2.8257940591066668;
  K[4] = ((L0 * 1.3010613912609821 - t2 * 31.81510986890008) +
          t3 * 91.0612095080102) -
         0.026038601136868081;
  K[5] = ((L0 * 29.100291966553609 - t2 * 75.453733352318281) -
          t3 * 141.10996241985549) +
         1.8197104007708369;
  K[6] = ((L0 * 6.9297614456680687 - t2 * 173.5470171297068) +
          t3 * 503.26885013269509) -
         0.162819403590846;
  K[7] = ((L0 * 92.493005915738237 + t2 * 70.740591872183273) -
          t3 * 2082.4149998744788) +
         13.53727401123562;
  K[8] = ((L0 * -5.2683188223664228 + t2 * 12.31682327416196) -
          t3 * 491.36037228712348) +
         23.86260049490588;
  K[9] = ((L0 * -80.567991028714928 + t2 * 3921.0168706884929) -
          t3 * 8473.40363213402) +
         27.609742883246469;
  K[10] = ((L0 * -19.387877205458128 + t2 * 115.2043671309067) -
           t3 * 301.04108386666292) +
          3.1829364712906951;
  K[11] = ((L0 * -21.4433056735076 + t2 * 290.64673412465532) -
           t3 * 542.39329956244649) +
          1.3746136079543949;
}


/* Function Definitions */
/*
 * LEG_J_CAL
 *     J = LEG_J_CAL(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float J[4]
 * Return Type  : void
 */
void leg_J_cal(float phi1, float phi4, float J[4])
{
	float t10;
  float t12;
  float t2;
  float t21;
  float t22;
  float t23;
  float t24;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t35;
  float t36;
  float t37;
  float t38;
  float t4;
  float t5;
  float t51;
  float t59;
  float t60;
  float t64;
  float t65;
  float t66;
  float t73;
  /* leg_J_2 */
  /*     J = leg_J_2(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-02-03 17:11:03 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10 = t2 * 0.215;
  t12 = t4 * 0.215;
  t21 = t2 * 0.10965;
  t22 = t3 * 0.10965;
  t23 = t4 * 0.10965;
  t24 = t5 * 0.10965;
  t29 = t10 - t3 * 0.215;
  t30 = t12 - t5 * 0.215;
  t33 = t21 - t22;
  t34 = t23 - t24;
  t35 = t4 * t29 * 0.43;
  t36 = t5 * t29 * 0.43;
  t37 = t2 * t30 * 0.43;
  t38 = t3 * t30 * 0.43;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0 / ((t22 - t21) + t51);
  t60 = t59 * t59;
  t64 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t65 = 1.0 / t64;
  t66 = (t24 - t23) + t64;
  t73 = atanf(t59 * t66) * 2.0;
  t30 = cosf(t73);
  t64 = sinf(t73);
  t73 = 1.0 / (t60 * (t66 * t66) + 1.0);
  t23 = ((t23 + t37) - t35) * t60 * t66 +
        t59 * (t21 - t65 *
                         ((t2 * t34 * 0.2193 - t4 * t33 * 0.2193) +
                          t51 * (t35 - t37) * 2.0) /
                         2.0);
  t29 = ((t24 + t38) - t36) * t60 * t66 +
        t59 * (t22 - t65 *
                         ((t3 * t34 * 0.2193 - t5 * t33 * 0.2193) +
                          t51 * (t36 - t38) * 2.0) /
                         2.0);
  t4 = t10 + t30 * 0.255;
  t21 = t12 + t64 * 0.255;
  t66 = t30 * t73;
  t2 = t66 * t29;
  t64 *= t73;
  t51 = t64 * t29;
  t59 = t4 * t4;
  t60 = 1.0 / t4;
  t30 = t21 * t21 + t59;
  t65 = 1.0 / sqrtf(t30);
  t73 = 1.0 / t30;
  t66 = t10 - t66 * t23 * 0.51;
  t29 = t12 - t64 * t23 * 0.51;
  J[0] = t65 * (t21 * t66 * 2.0 - t4 * t29 * 2.0) / 2.0;
  t30 = t21 * (1.0 / t59);
  J[1] = t59 * t73 * (t60 * t66 + t30 * t29);
  J[2] = t65 * (t21 * t2 * 1.02 - t4 * t51 * 1.02) / 2.0;
  J[3] = -t59 * t73 * (t60 * (0.0 - t2 * 0.51) - t30 * (t51 * 0.51));
}




void VMC_Data_Get(Leg_State_t* Leg_State , float phi4, float dphi4, float phi1, float dphi1)//整合位置，速度，雅可比矩阵的求解
{
    Leg_State->last_dl0 = Leg_State->this_dl0;
    Leg_State->phi4 = phi4;
    Leg_State->phi1 = phi1;
    Leg_State->dphi4 = dphi4;
    Leg_State->dphi1 = dphi1;

    leg_pos(phi1,phi4,Leg_State->pos);
    Leg_State->l0 = Leg_State->pos[0];
    Leg_State->phi0 = Leg_State->pos[1];
    Leg_State->phi0 = AngleWrap(Leg_State->phi0-1.57f);
    leg_spd(Leg_State->dphi1, Leg_State->dphi4, Leg_State->phi1, Leg_State->phi4, Leg_State->spd);
    Leg_State->dl0 = Leg_State->spd[0];
    Leg_State->this_dl0 = Leg_State->dl0;
    Leg_State->dphi0 = Leg_State->spd[1];
    Leg_State->ddl0 = (Leg_State->this_dl0 - Leg_State->last_dl0) / (TIME_STEP * 0.001);//可能要加低通滤波器

    leg_J_cal(phi1,phi4,Leg_State->J);
    for (int i = 0; i < 2; i++)
    {
        for (int j = 0; j < 2; j++)
        {
                Leg_State->j[j][i] = Leg_State->J[i * 2 + j];
        }
    }
}



float Get_Left_GasSpring_FN(float Left_Leglength)
{
    float Left_FN;
    Left_FN = 1.311e+07 * powf(Left_Leglength,6) - 1.8225e+07 * powf(Left_Leglength,5) + 1.0145e+07 * powf(Left_Leglength,4) -
    2.8776e+06 * powf(Left_Leglength,3) + 4.3630e+05 * powf(Left_Leglength,2) - 3.3513e+4*powf(Left_Leglength,1) + 955.5439;
    return Left_FN;
}




float Get_Right_GasSpring_FN(float Right_Leglength)
{
    float Right_FN;
    Right_FN = 3.6282e+06 * powf(Right_Leglength,6) - 2.7716e+06 * powf(Right_Leglength,5) + 9.5325e+04 * powf(Right_Leglength,4) +
    4.5222e+05 * powf(Right_Leglength,3) - 1.5418e+05 * powf(Right_Leglength,2) + 1.9290e+04*powf(Right_Leglength,1) -902.1393 ;
    return Right_FN;
}







