#include "main.h"

/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:02:27
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t110;
  float t112;
  float t118;
  float t130;
  float t133;
  float t141;
  float t16;
  float t18;
  float t21;
  float t22;
  float t24;
  float t25;
  float t4;
  float t49;
  float t5;
  float t50;
  float t55;
  float t56;
  float t6;
  float t63;
  float t64;
  float t65;
  float t66;
  float t7;
  float t91;
  /* LEG_CONV */
  /*     T = LEG_CONV(F,Tp,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:22 */
  t4 = cosf(phi1);
  t5 = cosf(phi4);
  t6 = sinf(phi1);
  t7 = sinf(phi4);
  t16 = t4 * 0.21F;
  t18 = t6 * 0.21F;
  t21 = t4 * 0.1008F;
  t22 = t5 * 0.1008F;
  t24 = t6 * 0.1008F;
  t25 = t7 * 0.1008F;
  t49 = t16 - t5 * 0.21F;
  t50 = t18 - t7 * 0.21F;
  t55 = t21 - t22;
  t56 = t24 - t25;
  t63 = t6 * t49 * 0.42F;
  t64 = t7 * t49 * 0.42F;
  t65 = t4 * t50 * 0.42F;
  t66 = t5 * t50 * 0.42F;
  t91 = t49 * t49 + t50 * t50;
  t49 = 1.0F / ((t22 - t21) + t91);
  t50 = t49 * t49;
  t110 = sqrtf((t55 * t55 + t56 * t56) - t91 * t91);
  t112 = 1.0F / t110;
  t118 = (t25 - t24) + t110;
  t130 = atanf(t49 * t118) * 2.0F;
  t133 = cosf(t130);
  t130 = sinf(t130);
  t141 = 1.0F / (t50 * (t118 * t118) + 1.0F);
  t110 = ((t24 + t65) - t63) * t50 * t118 +
         t49 * (t21 - t112 *
                          ((t4 * t56 * 0.2016F - t6 * t55 * 0.2016F) +
                           t91 * (t63 - t65) * 2.0F) /
                          2.0F);
  t6 = ((t25 + t66) - t64) * t50 * t118 +
       t49 * (t22 - t112 *
                        ((t5 * t56 * 0.2016F - t7 * t55 * 0.2016F) +
                         t91 * (t64 - t66) * 2.0F) /
                        2.0F);
  t21 = t16 + t133 * 0.24F;
  t24 = t18 + t130 * 0.24F;
  t112 = t21 * t21;
  t63 = 1.0F / t21;
  t118 = t24 * t24 + t112;
  t4 = t133 * t141;
  t91 = t16 - t4 * t110 * 0.48F;
  t130 *= t141;
  t50 = t18 - t130 * t110 * 0.48F;
  t110 = F * (1.0F / sqrtf(t118));
  t49 = Tp * t112 * (1.0F / t118);
  t118 = t24 * (1.0F / t112);
  T[0] = t110 * (t24 * t91 * 2.0F - t21 * t50 * 2.0F) / 2.0F +
         t49 * (t63 * t91 + t118 * t50);
  T[1] = t110 * (t4 * t24 * t6 * 0.96F - t130 * t21 * t6 * 0.96F) / 2.0F -
         t49 * (t63 * (0.0F - t4 * t6 * 0.48F) - t118 * (t130 * t6 * 0.48F));
}


/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:08:56
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void leg_pos(float phi1, float phi4, float pos[2])
{
  float t11;
  float t12;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;
  /* LEG_POS */
  /*     POS = LEG_POS(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:19 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t6 = t2 * 0.21F;
  t8 = t4 * 0.21F;
  t11 = t2 * 0.1008F;
  t12 = t3 * 0.1008F;
  t14 = t4 * 0.1008F;
  t15 = t5 * 0.1008F;
  t4 = t6 - t3 * 0.21F;
  t2 = t8 - t5 * 0.21F;
  t3 = t11 - t12;
  t5 = t14 - t15;
  t2 = t4 * t4 + t2 * t2;
  t2 = atanf(1.0F / ((t12 - t11) + t2) *
             ((t15 - t14) + sqrtf((t3 * t3 + t5 * t5) - t2 * t2))) *
       2.0F;
  t4 = t8 + sinf(t2) * 0.24F;
  t2 = t6 + cosf(t2) * 0.24F;
  pos[0] = sqrtf(t4 * t4 + t2 * t2);
  pos[1] = atan2f(t4, t2);
}



/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-19 15:34:42
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : float dphi1
 *                float dphi4
 *                float phi1
 *                float phi4
 *                float spd[2]
 * Return Type  : void
 */
void leg_spd(float dphi1, float dphi4, float phi1, float phi4, float spd[2])
{
  float t10;
  float t12;
  float t15;
  float t16;
  float t18;
  float t19;
  float t2;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t37;
  float t38;
  float t39;
  float t4;
  float t40;
  float t5;
  float t51;
  float t59;
  float t60;
  float t62;
  float t66;
  float t73;
  /* LEG_SPD */
  /*     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:21 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10 = t2 * 0.21F;
  t12 = t4 * 0.21F;
  t15 = t2 * 0.1008F;
  t16 = t3 * 0.1008F;
  t18 = t4 * 0.1008F;
  t19 = t5 * 0.1008F;
  t29 = t10 - t3 * 0.21F;
  t30 = t12 - t5 * 0.21F;
  t33 = t15 - t16;
  t34 = t18 - t19;
  t37 = t4 * t29 * 0.42F;
  t38 = t5 * t29 * 0.42F;
  t39 = t2 * t30 * 0.42F;
  t40 = t3 * t30 * 0.42F;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0F / ((t16 - t15) + t51);
  t60 = t59 * t59;
  t62 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t29 = 1.0F / t62;
  t66 = (t19 - t18) + t62;
  t73 = atanf(t59 * t66) * 2.0F;
  t30 = cosf(t73);
  t62 = sinf(t73);
  t73 = 1.0F / (t60 * (t66 * t66) + 1.0F);
  t18 = ((t18 + t39) - t37) * t60 * t66 +
        t59 * (t15 - t29 *
                         ((t2 * t34 * 0.2016F - t4 * t33 * 0.2016F) +
                          t51 * (t37 - t39) * 2.0F) /
                         2.0F);
  t29 = ((t19 + t40) - t38) * t60 * t66 +
        t59 * (t16 - t29 *
                         ((t3 * t34 * 0.2016F - t5 * t33 * 0.2016F) +
                          t51 * (t38 - t40) * 2.0F) /
                         2.0F);
  t2 = t10 + t30 * 0.24F;
  t4 = t12 + t62 * 0.24F;
  t66 = t30 * t73;
  t15 = t66 * t29;
  t62 *= t73;
  t51 = t62 * t29;
  t59 = t2 * t2;
  t60 = 1.0F / t2;
  t30 = t4 * t4 + t59;
  t29 = 1.0F / sqrtf(t30);
  t73 = 1.0F / t30;
  t66 = t10 - t66 * t18 * 0.48F;
  t30 = t12 - t62 * t18 * 0.48F;
  spd[0] = dphi4 * t29 * (t4 * t15 * 0.96F - t2 * t51 * 0.96F) / 2.0F +
           dphi1 * t29 * (t4 * t66 * 2.0F - t2 * t30 * 2.0F) / 2.0F;
  t29 = t4 * (1.0F / t59);
  spd[1] =
      dphi1 * t59 * t73 * (t60 * t66 + t29 * t30) -
      dphi4 * t59 * t73 * (t60 * (0.0F - t15 * 0.48F) - t29 * (t51 * 0.48F));
}


/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
uint8_t flag1;
void lqr_k(float L0, float K[12])//根据腿长得出LQR增益K
{
    float t2;
    float t3;
    /*     This function was generated by the Symbolic Math Toolbox version 25.1.
    */
    /*     2026-04-21 19:40:05 */
    t2 = L0 * L0;
    t3 = L0 * L0 * L0;

    if(Chassis.Leg_Length == HIGH_LEG_LENGTH)
    {
        if(Chassis.Chassis_Ref.V_y == 0 && fabs(Chassis.balance_loop.dx) < 0.3f && fabs(Chassis.Chassis_Ref.V_w) <= 0.5f)
        {
            K[0] = ((L0 * 22.676968490462631 - t2 * 317.843410448173) +
                  t3 * 378.260666165621) -
                 3.0107513843356588;
            K[1] = ((L0 * 2059.5198789873129 - t2 * 2736.634950424555) -
                  t3 * 609.33690416916943) +
                 12.728358005912231;
            K[2] = ((L0 * 5.24993783113196 - t2 * 30.70284459581028) +
                  t3 * 25.598561135987239) -
                 0.26976168263345152;
            K[3] = ((L0 * 57.895724187521637 + t2 * 307.33095085499531) -
                  t3 * 606.66933035594468) +
                 2.148918988391705;
            K[4] = ((L0 * 1.382327768698544 - t2 * 14.49594663234941) +
                  t3 * 17.930528719031471) +
                 0.38168095503971938;
            K[5] = ((L0 * 71.7702832175622 - t2 * 116.45635547106291) -
                  t3 * 5.6287886476226774) +
                 5.1239868604774621;
            K[6] = ((L0 * 3.3572918825224778 - t2 * 37.587916558612527) +
                  t3 * 46.443849145492607) +
                 1.026022536001131;
            K[7] = ((L0 * 181.54058264066981 - t2 * 275.10593629101908) -
                  t3 * 52.430641148558031) +
                 14.58210812003917;
            K[8] = ((L0 * 11.1489143414778 + t2 * 1.6884088657558609) -
                  t3 * 46.244852396685708) +
                 3.4798457865985211;
            K[9] = ((L0 * -720.19752832425047 + t2 * 4526.70525086368) -
                  t3 * 5349.3832118098) -
                 35.200284116918219;
            K[10] = ((L0 * -1.449233346311076 + t2 * 8.70414214232103) -
                   t3 * 13.398126437024279) +
                  0.62027422826918255;
            K[11] = ((L0 * -43.364166648483589 + t2 * 310.15488714096023) -
                   t3 * 354.71939141415248) -
                  11.06697380436065;
                  flag1++;
        }
        else
        {
            K[1] = ((L0 * 979.05515445693447 - t2 * 4183.3764447849517) +
                  t3 * 4776.2400218196763) +
                 58.202773998332987;
            K[2] = ((L0 * -7.5890280764279057 - t2 * 20.84545810550004) +
                  t3 * 28.305622073502779) +
                 0.21259719218404349;
            K[3] = ((L0 * 109.52488723879181 - t2 * 329.40832084257642) +
                  t3 * 317.99760059138941) +
                 0.72870569791614925;
            K[4] = ((L0 * -17.49599367828494 + t2 * 32.014330234596081) -
                  t3 * 19.591442091160172) +
                 0.81271836162380806;
            K[5] = ((L0 * 77.674720252402338 - t2 * 404.72212190633718) +
                  t3 * 492.42335944846542) +
                 10.384807163585879;
            K[6] = ((L0 * -36.03691096900598 + t2 * 65.517400538102464) -
                  t3 * 40.8223324507127) +
                 1.543078395490922;
            K[7] = ((L0 * 128.86867414603171 - t2 * 737.91882876312161) +
                  t3 * 915.5021087291467) +
                 25.297232073963379;
            K[8] = ((L0 * -5.5227668307088917 - t2 * 283.14651117368737) +
                  t3 * 422.81046675167607) +
                 35.557234057124838;
            K[9] = ((L0 * 1348.604579916557 - t2 * 2136.5659021199372) +
                  t3 * 944.40540846143983) -
                 30.873246643187858;
            K[10] = ((L0 * -7.2423147630196034 + t2 * 5.5336498096032267) +
                   t3 * 0.679905418561699) +
                  3.075333722202457;
            K[11] = ((L0 * 52.008921263704607 - t2 * 58.541006117842777) -
                   t3 * 1.6541548143354841) -
                  2.6080955660922189;
      }
    }
    else if(Chassis.Leg_Length == MIDDLE_LEG_LENGTH)//中腿长
    {
        K[0] = ((L0 * -80.487668048635541 - t2 * 53.291634852699246) +
              t3 * 179.91697684551119) -
             1.438956909986661;
        K[1] = ((L0 * 2154.0141461327562 - t2 * 6901.6006950666233) +
              t3 * 6509.4549608598791) -
             3.50026345811754;
        K[2] = ((L0 * 0.53632354794384784 - t2 * 32.447733153241757) +
              t3 * 36.1500213423305) -
             0.097200274623645347;
        K[3] = ((L0 * 158.4572175762803 - t2 * 351.67656106857572) +
              t3 * 236.97193892652791) -
             1.371496574892499;
        K[4] = ((t2 * -8.97675923120045 + t3 * 18.9119511561124) -
              L0 * 3.1415926535897931 * 1.090308448496937) +
             0.46916434935300327;
        K[5] = ((L0 * 153.60778555569621 - t2 * 544.56278724283845) +
              t3 * 544.37044328583193) +
             3.3013391878996061;
        K[6] = ((L0 * -8.0331362956449812 - t2 * 16.46708004148509) +
              t3 * 36.900481550810873) +
             1.008780331336149;
        K[7] = ((L0 * 296.5156231136346 - t2 * 1071.261721238295) +
              t3 * 1073.864364072479) +
             10.702341238853419;
        K[8] = ((L0 * 28.39861196716933 - t2 * 149.0203409006692) +
              t3 * 145.8617361953186) +
             12.194213295513819;
        K[9] = ((L0 * 28.176545248186489 + t2 * 2068.671046369785) -
              t3 * 3199.64578825408) -
             4.6274835636135156;
        K[10] = ((L0 * -3.568472821198132 + t2 * 5.6361242845781776) -
               t3 * 5.9822745829027637) +
              1.7451453991411581;
        K[11] = ((L0 * -13.1752973191812 + t2 * 179.92595533769509) -
               t3 * 252.74303925363071) -
              2.0782978529782352;
    }
    else//低腿长
    {
        if(Chassis.Control_Mode == CHASSIS_CLOCKWISE_ROTATE  || Chassis.Control_Mode == CHASSIS_ANTI_CLOCKWISE_ROTATE)//逆时针旋转比较稳
        {
              K[0] = ((L0 * -176.49690125811031 + t2 * 226.09757179344541) -
                      t3 * 88.526932120602652) +
                     1.0716879806337429;
              K[1] = ((L0 * 1083.492705892922 - t2 * 4291.4714356604927) +
                      t3 * 4699.5629525275708) +
                     51.982636396184382;
              K[2] = ((L0 * -5.2043831814523278 - t2 * 27.909466962101408) +
                      t3 * 34.528028064087017) +
                     0.1218434493568686;
              K[3] = ((L0 * 112.09625377137181 - t2 * 303.7667426319847) +
                      t3 * 271.34023656582349) +
                     0.45745293917902019;
              K[4] = ((L0 * -15.06521033420286 + t2 * 21.661069372259242) -
                      t3 * 7.8339368729988914) +
                     0.8392504069401272;
              K[5] = ((L0 * 91.3767553073929 - t2 * 428.95093101569182) +
                      t3 * 499.00529730069462) +
                     9.64679466397243;
              K[6] = ((L0 * -31.241150854842822 + t2 * 44.839972199923352) -
                      t3 * 17.277903132839889) +
                     1.625351894237582;
              K[7] = ((L0 * 157.0453150868268 - t2 * 787.48912737491878) +
                      t3 * 928.887986673061) +
                     23.817168735187561;
              K[8] = ((L0 * 13.907569626669559 - t2 * 228.881716484069) +
                      t3 * 304.32130613601811) +
                     23.59802407745412;
              K[9] = ((L0 * 746.84837453837224 - t2 * 720.56249391702681) -
                      t3 * 195.9785145397619) -
                     18.232886705646681;
              K[10] = ((L0 * -5.1697211249046413 + t2 * 3.494716097639893) +
                       t3 * 0.36802732788669412) +
                      2.4907217377171089;
              K[11] = ((L0 * 35.978595766036577 - t2 * 15.295648273645361) -
                       t3 * 39.664123524281443) -
                      2.4782668997909751;
        }
        else
        {
            if(Chassis.Chassis_Ref.V_y == 0 && fabs(Chassis.balance_loop.dx) <= 0.45f && fabs(Chassis.Chassis_Ref.V_w) <= 0.5f )
            {  
                K[0] = ((L0 * 13.291070452429761 - t2 * 244.908169498452) +
                      t3 * 268.04302547217128) -
                     3.5678580857707192;
                K[1] = ((L0 * 5613.8876769404042 - t2 * 7523.4633417025016) -
                      t3 * 604.5510812178369) -
                     176.95701914183681;
                K[2] = ((L0 * 3.9630821007265342 - t2 * 23.9999452702524) +
                      t3 * 16.854055654667331) -
                     0.22439627054179109;
                K[3] = ((L0 * 179.0883430642869 + t2 * 586.11894348136627) -
                      t3 * 1242.9399191558639) -
                     3.976443313962617;
                K[4] = ((L0 * 1.34016066444552 - t2 * 11.80612969273343) +
                      t3 * 13.448761747161971) +
                     0.28209266543054551;
                K[5] = ((L0 * 238.01622191534179 - t2 * 449.1487240560981) +
                      t3 * 176.11035561795839) -
                     2.9652828672515441;
                K[6] = ((L0 * 3.3001045009320911 - t2 * 31.265622603607511) +
                      t3 * 35.538981323368709) +
                     0.79377599202323013;
                K[7] = ((L0 * 639.17690289313134 - t2 * 1185.4967908602671) +
                      t3 * 436.95154941854952) -
                     6.3789432219785711;
                K[8] = ((L0 * 4.3340422004829993 + t2 * 29.4641385220628) -
                      t3 * 82.725360800212627) +
                     6.020012367853135;
                K[9] = ((L0 * -3377.1279441505212 + t2 * 15452.261433178881) -
                      t3 * 16319.8665355459) +
                     93.450267625419883;
                K[10] = ((L0 * -3.22135853888225 + t2 * 12.6997924027502) -
                       t3 * 16.431824912706261) +
                      0.94448336938440647;
                K[11] = ((L0 * -329.52555046987231 + t2 * 1303.94233132017) -
                       t3 * 1338.7351512377061) +
                      0.3089356717804923;      
            }
            else
            {
                K[0] = ((L0 * -68.067572282939281 - t2 * 95.611625262611454) +
                      t3 * 234.52732531172171) -
                     1.6441513540068591;
                K[1] = ((L0 * 2700.3980965597639 - t2 * 8646.4470340472035) +
                      t3 * 8116.4299778936893) -
                     26.033178172014161;
                K[2] = ((L0 * 1.435029491893566 - t2 * 34.11154681701472) +
                      t3 * 39.101112644475442) -
                     0.12333689094086631;
                K[3] = ((L0 * 183.54093523136419 - t2 * 407.05693390349978) +
                      t3 * 261.759770437314) -
                     2.809951176735848;
                K[4] = ((L0 * -2.4432744097753192 - t2 * 9.7394374710306444) +
                      t3 * 19.1084415906952) +
                     0.42072876539231441;
                K[5] = ((L0 * 165.1943821773431 - t2 * 589.10605284002) +
                      t3 * 589.77065622406371) +
                     2.508048756896978;
                K[6] = ((L0 * -6.1458024044078048 - t2 * 20.07400112154685) +
                      t3 * 40.797560528676613) +
                     0.96891568152051255;
                K[7] = ((L0 * 348.60174998931268 - t2 * 1258.425919389867) +
                      t3 * 1260.865324514087) +
                     8.7426073990645232;
                K[8] = ((L0 * 41.935001458616043 - t2 * 205.6100164674213) +
                      t3 * 203.2599239327497) +
                     12.965764041636961;
                K[9] = ((L0 * -44.290529836869133 + t2 * 3720.5855965381552) -
                      t3 * 5725.340509583144) -
                     18.312500888893691;
                K[10] = ((L0 * -3.166849284193225 + t2 * 4.3332865609020281) -
                       t3 * 5.083446595008966) +
                      1.75645494555429;
                K[11] = ((L0 * -29.464552194889141 + t2 * 302.17890798258207) -
                       t3 * 418.61627308980229) -
                      3.8459554518321379;
            }
        }
    }
}


/* Function Definitions */
/*
 * LEG_J_CAL
 *     J = LEG_J_CAL(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float J[4]
 * Return Type  : void
 */
void leg_J_cal(float phi1, float phi4, float J[4])
{
	float t10;
  float t12;
  float t2;
  float t21;
  float t22;
  float t23;
  float t24;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t35;
  float t36;
  float t37;
  float t38;
  float t4;
  float t5;
  float t51;
  float t59;
  float t60;
  float t64;
  float t65;
  float t66;
  float t73;
  /* leg_J_2 */
  /*     J = leg_J_2(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-02-03 17:11:03 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10 = t2 * 0.215;
  t12 = t4 * 0.215;
  t21 = t2 * 0.10965;
  t22 = t3 * 0.10965;
  t23 = t4 * 0.10965;
  t24 = t5 * 0.10965;
  t29 = t10 - t3 * 0.215;
  t30 = t12 - t5 * 0.215;
  t33 = t21 - t22;
  t34 = t23 - t24;
  t35 = t4 * t29 * 0.43;
  t36 = t5 * t29 * 0.43;
  t37 = t2 * t30 * 0.43;
  t38 = t3 * t30 * 0.43;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0 / ((t22 - t21) + t51);
  t60 = t59 * t59;
  t64 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t65 = 1.0 / t64;
  t66 = (t24 - t23) + t64;
  t73 = atanf(t59 * t66) * 2.0;
  t30 = cosf(t73);
  t64 = sinf(t73);
  t73 = 1.0 / (t60 * (t66 * t66) + 1.0);
  t23 = ((t23 + t37) - t35) * t60 * t66 +
        t59 * (t21 - t65 *
                         ((t2 * t34 * 0.2193 - t4 * t33 * 0.2193) +
                          t51 * (t35 - t37) * 2.0) /
                         2.0);
  t29 = ((t24 + t38) - t36) * t60 * t66 +
        t59 * (t22 - t65 *
                         ((t3 * t34 * 0.2193 - t5 * t33 * 0.2193) +
                          t51 * (t36 - t38) * 2.0) /
                         2.0);
  t4 = t10 + t30 * 0.255;
  t21 = t12 + t64 * 0.255;
  t66 = t30 * t73;
  t2 = t66 * t29;
  t64 *= t73;
  t51 = t64 * t29;
  t59 = t4 * t4;
  t60 = 1.0 / t4;
  t30 = t21 * t21 + t59;
  t65 = 1.0 / sqrtf(t30);
  t73 = 1.0 / t30;
  t66 = t10 - t66 * t23 * 0.51;
  t29 = t12 - t64 * t23 * 0.51;
  J[0] = t65 * (t21 * t66 * 2.0 - t4 * t29 * 2.0) / 2.0;
  t30 = t21 * (1.0 / t59);
  J[1] = t59 * t73 * (t60 * t66 + t30 * t29);
  J[2] = t65 * (t21 * t2 * 1.02 - t4 * t51 * 1.02) / 2.0;
  J[3] = -t59 * t73 * (t60 * (0.0 - t2 * 0.51) - t30 * (t51 * 0.51));
}




void VMC_Data_Get(Leg_State_t* Leg_State , float phi4, float dphi4, float phi1, float dphi1)//整合位置，速度，雅可比矩阵的求解
{
    Leg_State->last_dl0 = Leg_State->this_dl0;
    Leg_State->phi4 = phi4;
    Leg_State->phi1 = phi1;
    Leg_State->dphi4 = dphi4;
    Leg_State->dphi1 = dphi1;

    leg_pos(phi1,phi4,Leg_State->pos);
    Leg_State->l0 = Leg_State->pos[0];
    Leg_State->phi0 = Normalize_Angle_PI(Leg_State->pos[1]-1.57f);
    leg_spd(Leg_State->dphi1, Leg_State->dphi4, Leg_State->phi1, Leg_State->phi4, Leg_State->spd);
    Leg_State->dl0 = Leg_State->spd[0];
    Leg_State->this_dl0 = Leg_State->dl0;
    Leg_State->dphi0 = Leg_State->spd[1];
    Leg_State->ddl0 = (Leg_State->this_dl0 - Leg_State->last_dl0) / (TIME_STEP * 0.001);//可能要加低通滤波器

    leg_J_cal(phi1,phi4,Leg_State->J);
    for (int i = 0; i < 2; i++)
    {
        for (int j = 0; j < 2; j++)
        {
                Leg_State->j[j][i] = Leg_State->J[i * 2 + j];
        }
    }
}



float Get_Left_GasSpring_FN(float Left_Leglength)
{
    float Left_FN;
    Left_FN = 1.311e+07 * powf(Left_Leglength,6) - 1.8225e+07 * powf(Left_Leglength,5) + 1.0145e+07 * powf(Left_Leglength,4) -
    2.8776e+06 * powf(Left_Leglength,3) + 4.3630e+05 * powf(Left_Leglength,2) - 3.3513e+4*powf(Left_Leglength,1) + 955.5439;
    return Left_FN;
}




float Get_Right_GasSpring_FN(float Right_Leglength)
{
    float Right_FN;
    Right_FN = 3.6282e+06 * powf(Right_Leglength,6) - 2.7716e+06 * powf(Right_Leglength,5) + 9.5325e+04 * powf(Right_Leglength,4) +
    4.5222e+05 * powf(Right_Leglength,3) - 1.5418e+05 * powf(Right_Leglength,2) + 1.9290e+04*powf(Right_Leglength,1) -902.1393 ;
    return Right_FN;
}







