#include "main.h"

/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_conv.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:02:27
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_CONV
 *     T = LEG_CONV(F,Tp,PHI1,PHI4)
 *
 * Arguments    : float F
 *                float Tp
 *                float phi1
 *                float phi4
 *                float T[2]
 * Return Type  : void
 */
void leg_conv(float F, float Tp, float phi1, float phi4, float T[2])
{
  float t110;
  float t112;
  float t118;
  float t130;
  float t133;
  float t141;
  float t16;
  float t18;
  float t21;
  float t22;
  float t24;
  float t25;
  float t4;
  float t49;
  float t5;
  float t50;
  float t55;
  float t56;
  float t6;
  float t63;
  float t64;
  float t65;
  float t66;
  float t7;
  float t91;
  /* LEG_CONV */
  /*     T = LEG_CONV(F,Tp,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:22 */
  t4 = cosf(phi1);
  t5 = cosf(phi4);
  t6 = sinf(phi1);
  t7 = sinf(phi4);
  t16 = t4 * 0.21F;
  t18 = t6 * 0.21F;
  t21 = t4 * 0.1008F;
  t22 = t5 * 0.1008F;
  t24 = t6 * 0.1008F;
  t25 = t7 * 0.1008F;
  t49 = t16 - t5 * 0.21F;
  t50 = t18 - t7 * 0.21F;
  t55 = t21 - t22;
  t56 = t24 - t25;
  t63 = t6 * t49 * 0.42F;
  t64 = t7 * t49 * 0.42F;
  t65 = t4 * t50 * 0.42F;
  t66 = t5 * t50 * 0.42F;
  t91 = t49 * t49 + t50 * t50;
  t49 = 1.0F / ((t22 - t21) + t91);
  t50 = t49 * t49;
  t110 = sqrtf((t55 * t55 + t56 * t56) - t91 * t91);
  t112 = 1.0F / t110;
  t118 = (t25 - t24) + t110;
  t130 = atanf(t49 * t118) * 2.0F;
  t133 = cosf(t130);
  t130 = sinf(t130);
  t141 = 1.0F / (t50 * (t118 * t118) + 1.0F);
  t110 = ((t24 + t65) - t63) * t50 * t118 +
         t49 * (t21 - t112 *
                          ((t4 * t56 * 0.2016F - t6 * t55 * 0.2016F) +
                           t91 * (t63 - t65) * 2.0F) /
                          2.0F);
  t6 = ((t25 + t66) - t64) * t50 * t118 +
       t49 * (t22 - t112 *
                        ((t5 * t56 * 0.2016F - t7 * t55 * 0.2016F) +
                         t91 * (t64 - t66) * 2.0F) /
                        2.0F);
  t21 = t16 + t133 * 0.24F;
  t24 = t18 + t130 * 0.24F;
  t112 = t21 * t21;
  t63 = 1.0F / t21;
  t118 = t24 * t24 + t112;
  t4 = t133 * t141;
  t91 = t16 - t4 * t110 * 0.48F;
  t130 *= t141;
  t50 = t18 - t130 * t110 * 0.48F;
  t110 = F * (1.0F / sqrtf(t118));
  t49 = Tp * t112 * (1.0F / t118);
  t118 = t24 * (1.0F / t112);
  T[0] = t110 * (t24 * t91 * 2.0F - t21 * t50 * 2.0F) / 2.0F +
         t49 * (t63 * t91 + t118 * t50);
  T[1] = t110 * (t4 * t24 * t6 * 0.96F - t130 * t21 * t6 * 0.96F) / 2.0F -
         t49 * (t63 * (0.0F - t4 * t6 * 0.48F) - t118 * (t130 * t6 * 0.48F));
}


/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_pos.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-13 13:08:56
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_POS
 *     POS = LEG_POS(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float pos[2]
 * Return Type  : void
 */
void leg_pos(float phi1, float phi4, float pos[2])
{
  float t11;
  float t12;
  float t14;
  float t15;
  float t2;
  float t3;
  float t4;
  float t5;
  float t6;
  float t8;
  /* LEG_POS */
  /*     POS = LEG_POS(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:19 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t6 = t2 * 0.21F;
  t8 = t4 * 0.21F;
  t11 = t2 * 0.1008F;
  t12 = t3 * 0.1008F;
  t14 = t4 * 0.1008F;
  t15 = t5 * 0.1008F;
  t4 = t6 - t3 * 0.21F;
  t2 = t8 - t5 * 0.21F;
  t3 = t11 - t12;
  t5 = t14 - t15;
  t2 = t4 * t4 + t2 * t2;
  t2 = atanf(1.0F / ((t12 - t11) + t2) *
             ((t15 - t14) + sqrtf((t3 * t3 + t5 * t5) - t2 * t2))) *
       2.0F;
  t4 = t8 + sinf(t2) * 0.24F;
  t2 = t6 + cosf(t2) * 0.24F;
  pos[0] = sqrtf(t4 * t4 + t2 * t2);
  pos[1] = atan2f(t4, t2);
}



/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: leg_spd.c
 *
 * MATLAB Coder version            : 25.1
 * C/C++ source code generated on  : 2026-04-19 15:34:42
 */

/* Include Files */

/* Function Definitions */
/*
 * LEG_SPD
 *     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4)
 *
 * Arguments    : float dphi1
 *                float dphi4
 *                float phi1
 *                float phi4
 *                float spd[2]
 * Return Type  : void
 */
void leg_spd(float dphi1, float dphi4, float phi1, float phi4, float spd[2])
{
  float t10;
  float t12;
  float t15;
  float t16;
  float t18;
  float t19;
  float t2;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t37;
  float t38;
  float t39;
  float t4;
  float t40;
  float t5;
  float t51;
  float t59;
  float t60;
  float t62;
  float t66;
  float t73;
  /* LEG_SPD */
  /*     SPD = LEG_SPD(DPHI1,DPHI4,PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-01-04 11:05:21 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10 = t2 * 0.21F;
  t12 = t4 * 0.21F;
  t15 = t2 * 0.1008F;
  t16 = t3 * 0.1008F;
  t18 = t4 * 0.1008F;
  t19 = t5 * 0.1008F;
  t29 = t10 - t3 * 0.21F;
  t30 = t12 - t5 * 0.21F;
  t33 = t15 - t16;
  t34 = t18 - t19;
  t37 = t4 * t29 * 0.42F;
  t38 = t5 * t29 * 0.42F;
  t39 = t2 * t30 * 0.42F;
  t40 = t3 * t30 * 0.42F;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0F / ((t16 - t15) + t51);
  t60 = t59 * t59;
  t62 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t29 = 1.0F / t62;
  t66 = (t19 - t18) + t62;
  t73 = atanf(t59 * t66) * 2.0F;
  t30 = cosf(t73);
  t62 = sinf(t73);
  t73 = 1.0F / (t60 * (t66 * t66) + 1.0F);
  t18 = ((t18 + t39) - t37) * t60 * t66 +
        t59 * (t15 - t29 *
                         ((t2 * t34 * 0.2016F - t4 * t33 * 0.2016F) +
                          t51 * (t37 - t39) * 2.0F) /
                         2.0F);
  t29 = ((t19 + t40) - t38) * t60 * t66 +
        t59 * (t16 - t29 *
                         ((t3 * t34 * 0.2016F - t5 * t33 * 0.2016F) +
                          t51 * (t38 - t40) * 2.0F) /
                         2.0F);
  t2 = t10 + t30 * 0.24F;
  t4 = t12 + t62 * 0.24F;
  t66 = t30 * t73;
  t15 = t66 * t29;
  t62 *= t73;
  t51 = t62 * t29;
  t59 = t2 * t2;
  t60 = 1.0F / t2;
  t30 = t4 * t4 + t59;
  t29 = 1.0F / sqrtf(t30);
  t73 = 1.0F / t30;
  t66 = t10 - t66 * t18 * 0.48F;
  t30 = t12 - t62 * t18 * 0.48F;
  spd[0] = dphi4 * t29 * (t4 * t15 * 0.96F - t2 * t51 * 0.96F) / 2.0F +
           dphi1 * t29 * (t4 * t66 * 2.0F - t2 * t30 * 2.0F) / 2.0F;
  t29 = t4 * (1.0F / t59);
  spd[1] =
      dphi1 * t59 * t73 * (t60 * t66 + t29 * t30) -
      dphi4 * t59 * t73 * (t60 * (0.0F - t15 * 0.48F) - t29 * (t51 * 0.48F));
}


/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : float L0
 *                float K[12]
 * Return Type  : void
 */
uint8_t flag1;
void lqr_k(float L0, float K[12])//根据腿长得出LQR增益K
{
    float t2;
    float t3;
    /*     This function was generated by the Symbolic Math Toolbox version 25.1.
    */
    /*     2026-04-21 19:40:05 */
    t2 = L0 * L0;
    t3 = L0 * L0 * L0;

    if(Chassis.USART_Chassis_Data.Cmd_Leg_Length == HIGH_LEGLENGTH_CMD)
    {
        if(/*Chassis.Control_Mode == CHASSIS_STOP*/Chassis.Chassis_Ref.V_y == 0 && fabs(Chassis.balance_loop.dx) < 0.5f && fabs(Chassis.Chassis_Ref.V_w) <= 3.0f)
        {
   K[0] = ((L0 * 23.63249402687843 - t2 * 280.98625454799031) +
          t3 * 309.88357372621192) -
         2.6109091826157882;
  K[1] = ((L0 * 1296.376093082913 - t2 * 575.94502585767862) -
          t3 * 2186.5026212485968) +
         30.42811118123738;
  K[2] = ((L0 * 4.4973910624444589 - t2 * 24.354380370232061) +
          t3 * 17.433755167396381) -
         0.22414267922965189;
  K[3] = ((L0 * 20.901759257557291 + t2 * 334.86625952800858) -
          t3 * 545.78423092676212) +
         3.135242780763503;
  K[4] = ((L0 * 1.106175276442356 - t2 * 10.85511249022591) +
          t3 * 12.627332844516729) +
         0.36170358805180242;
  K[5] = ((L0 * 34.366490505110278 - t2 * 12.21871206082349) -
          t3 * 78.119284521240587) +
         4.3947404006620552;
  K[6] = ((L0 * 2.9011577386071541 - t2 * 30.038947631137219) +
          t3 * 34.830147395821378) +
         1.03007770465056;
  K[7] = ((L0 * 91.847405556596328 - t2 * 13.27747435618414) -
          t3 * 244.3631163355378) +
         12.997846984076761;
  K[8] = ((L0 * 6.8279503713925944 + t2 * 17.52165895783105) -
          t3 * 55.88065654455702) +
         2.665941023598867;
  K[9] = ((L0 * -446.55188451302632 + t2 * 2811.668957942712) -
          t3 * 3184.7415496955632) -
         39.7550830517246;
  K[10] = ((L0 * -1.305887194926709 + t2 * 9.16065018665115) -
           t3 * 13.816794172149139) +
          0.52818681025925462;
  K[11] = ((L0 * -17.39277698847172 + t2 * 176.7125634809112) -
           t3 * 187.98578556111511) -
          11.5558090755398;
        }
        else
        {
   K[0] = ((L0 * -205.9695884155791 + t2 * 295.81567563121013) -
          t3 * 157.55385257865379) +
         1.147955208020969;
  K[1] = ((L0 * 1443.3845256544721 - t2 * 5543.2065425257442) +
          t3 * 6076.9033799124963) +
         33.59276303444333;
  K[2] = ((L0 * -8.43499366150169 - t2 * 27.40389241341127) +
          t3 * 34.824644837269247) +
         0.24631451691572859;
  K[3] = ((L0 * 159.85938231459849 - t2 * 452.85960470210722) +
          t3 * 425.05569451433468) -
         1.0141882680378109;
  K[4] = ((L0 * -18.301551828237169 + t2 * 31.641736408290068) -
          t3 * 17.921176804839771) +
         0.80206374382318435;
  K[5] = ((L0 * 130.80810772241631 - t2 * 577.27207191059426) +
          t3 * 668.427718404502) +
         7.6891732425832391;
  K[6] = ((L0 * -41.676886331034552 + t2 * 70.844042279767748) -
          t3 * 40.3661418260038) +
         1.687536798890708;
  K[7] = ((L0 * 272.3514274487668 - t2 * 1237.502314704539) +
          t3 * 1443.7773373468069) +
         21.24589784141649;
  K[8] = ((L0 * -12.541449913180159 - t2 * 418.622549203637) +
          t3 * 619.01045133010143) +
         58.923852615921213;
  K[9] = ((L0 * 2116.7008726283111 - t2 * 2988.9730343048841) +
          t3 * 956.46819889530877) -
         30.075487421413669;
  K[10] = ((L0 * -11.64064363967284 + t2 * 13.139693234543021) -
           t3 * 5.1468844628190409) +
          4.4952420096732633;
  K[11] = ((L0 * 57.9524813748918 - t2 * 38.111387980876508) -
           t3 * 44.237058447807733) -
          1.285895530889283;
      }
    }
    else if(Chassis.USART_Chassis_Data.Cmd_Leg_Length == MIDDLE_LEGLENGTH_CMD)//中腿长
    {
  K[0] = ((L0 * -174.81758450658739 + t2 * 215.11408493418941) -
          t3 * 82.970137392999) +
         0.17833295229812879;
  K[1] = ((L0 * 1493.800789975458 - t2 * 5411.1079526721769) +
          t3 * 5730.3767335019465) +
         13.127158854113439;
  K[2] = ((L0 * -7.1793365954740356 - t2 * 26.57517191309968) +
          t3 * 33.455432517697979) +
         0.189432465512285;
  K[3] = ((L0 * 159.729225300726 - t2 * 444.85632786886327) +
          t3 * 408.77445048275871) -
         1.153285895717024;
  K[4] = ((L0 * -11.43510402143003 + t2 * 16.31105233304697) -
          t3 * 5.9852635734908484) +
         0.54832562032498844;
  K[5] = ((L0 * 108.1266492296381 - t2 * 442.7930803243724) +
          t3 * 494.77482776817368) +
         3.959040287567988;
  K[6] = ((L0 * -32.08872197547911 + t2 * 45.038406418820067) -
          t3 * 16.6702222924401) +
         1.448192088444004;
  K[7] = ((L0 * 286.65528620335209 - t2 * 1191.763965888566) +
          t3 * 1336.991827920165) +
         13.567631110201949;
  K[8] = ((L0 * 9.496458618790049 - t2 * 347.97512464668893) +
          t3 * 471.237929302583) +
         43.4000578701421;
  K[9] = ((L0 * 1312.869955419178 - t2 * 1188.022209442559) -
          t3 * 424.825241701902) -
         10.00582312764374;
  K[10] = ((L0 * -9.6837667191052645 + t2 * 11.616211352815119) -
           t3 * 5.9940947482216744) +
          3.854711785813961;
  K[11] = ((L0 * 35.863621581704393 + t2 * 15.977151753714461) -
           t3 * 88.624132318831371) -
          0.26491420588151188;
    }
    else//低腿长
    {
        if(Chassis.Control_Mode == CHASSIS_CLOCKWISE_ROTATE  || Chassis.Control_Mode == CHASSIS_ANTI_CLOCKWISE_ROTATE)
        {
              K[0] = ((L0 * -176.49690125811031 + t2 * 226.09757179344541) -
                      t3 * 88.526932120602652) +
                     1.0716879806337429;
              K[1] = ((L0 * 1083.492705892922 - t2 * 4291.4714356604927) +
                      t3 * 4699.5629525275708) +
                     51.982636396184382;
              K[2] = ((L0 * -5.2043831814523278 - t2 * 27.909466962101408) +
                      t3 * 34.528028064087017) +
                     0.1218434493568686;
              K[3] = ((L0 * 112.09625377137181 - t2 * 303.7667426319847) +
                      t3 * 271.34023656582349) +
                     0.45745293917902019;
              K[4] = ((L0 * -15.06521033420286 + t2 * 21.661069372259242) -
                      t3 * 7.8339368729988914) +
                     0.8392504069401272;
              K[5] = ((L0 * 91.3767553073929 - t2 * 428.95093101569182) +
                      t3 * 499.00529730069462) +
                     9.64679466397243;
              K[6] = ((L0 * -31.241150854842822 + t2 * 44.839972199923352) -
                      t3 * 17.277903132839889) +
                     1.625351894237582;
              K[7] = ((L0 * 157.0453150868268 - t2 * 787.48912737491878) +
                      t3 * 928.887986673061) +
                     23.817168735187561;
              K[8] = ((L0 * 13.907569626669559 - t2 * 228.881716484069) +
                      t3 * 304.32130613601811) +
                     23.59802407745412;
              K[9] = ((L0 * 746.84837453837224 - t2 * 720.56249391702681) -
                      t3 * 195.9785145397619) -
                     18.232886705646681;
              K[10] = ((L0 * -5.1697211249046413 + t2 * 3.494716097639893) +
                       t3 * 0.36802732788669412) +
                      2.4907217377171089;
              K[11] = ((L0 * 35.978595766036577 - t2 * 15.295648273645361) -
                       t3 * 39.664123524281443) -
                      2.4782668997909751;
        }
        else
        {
//            if(Chassis.Control_Mode == CHASSIS_STOP/*Chassis.Chassis_Ref.V_y == 0 && fabs(Chassis.balance_loop.dx) <= 0.45f && fabs(Chassis.Chassis_Ref.V_w) <= 0.5f*/)//暂时没用了
//            {  
//                K[0] = ((L0 * 13.291070452429761 - t2 * 244.908169498452) +
//                      t3 * 268.04302547217128) -
//                     3.5678580857707192;
//                K[1] = ((L0 * 5613.8876769404042 - t2 * 7523.4633417025016) -
//                      t3 * 604.5510812178369) -
//                     176.95701914183681;
//                K[2] = ((L0 * 3.9630821007265342 - t2 * 23.9999452702524) +
//                      t3 * 16.854055654667331) -
//                     0.22439627054179109;
//                K[3] = ((L0 * 179.0883430642869 + t2 * 586.11894348136627) -
//                      t3 * 1242.9399191558639) -
//                     3.976443313962617;
//                K[4] = ((L0 * 1.34016066444552 - t2 * 11.80612969273343) +
//                      t3 * 13.448761747161971) +
//                     0.28209266543054551;
//                K[5] = ((L0 * 238.01622191534179 - t2 * 449.1487240560981) +
//                      t3 * 176.11035561795839) -
//                     2.9652828672515441;
//                K[6] = ((L0 * 3.3001045009320911 - t2 * 31.265622603607511) +
//                      t3 * 35.538981323368709) +
//                     0.79377599202323013;
//                K[7] = ((L0 * 639.17690289313134 - t2 * 1185.4967908602671) +
//                      t3 * 436.95154941854952) -
//                     6.3789432219785711;
//                K[8] = ((L0 * 4.3340422004829993 + t2 * 29.4641385220628) -
//                      t3 * 82.725360800212627) +
//                     6.020012367853135;
//                K[9] = ((L0 * -3377.1279441505212 + t2 * 15452.261433178881) -
//                      t3 * 16319.8665355459) +
//                     93.450267625419883;
//                K[10] = ((L0 * -3.22135853888225 + t2 * 12.6997924027502) -
//                       t3 * 16.431824912706261) +
//                      0.94448336938440647;
//                K[11] = ((L0 * -329.52555046987231 + t2 * 1303.94233132017) -
//                       t3 * 1338.7351512377061) +
//                      0.3089356717804923;      
//            }
//            else
//            {
  K[0] = ((L0 * -96.728258556339057 + t2 * 1.196912023935863) +
          t3 * 113.8452554762422) -
         1.182241977215353;
  K[1] = ((L0 * 1770.931716322058 - t2 * 5631.4050733957429) +
          t3 * 5393.7709998229611) +
         1.337318939364045;
  K[2] = ((L0 * -0.45365493502015619 - t2 * 33.851359719952569) +
          t3 * 36.486731021847767) -
         0.05524439215170688;
  K[3] = ((L0 * 153.4142989619597 - t2 * 330.54011806845671) +
          t3 * 234.3193372128346) -
         1.080189540812168;
  K[4] = ((L0 * -5.7158220319328654 - t2 * 3.611522701138635) +
          t3 * 14.248154164643189) +
         0.58853537862361827;
  K[5] = ((L0 * 143.09338420141961 - t2 * 516.46208283684348) +
          t3 * 528.68557070729389) +
         4.0019684289561024;
  K[6] = ((L0 * -13.61257270345676 - t2 * 7.5200011649016414) +
          t3 * 31.461695267377149) +
         1.331957459217378;
  K[7] = ((L0 * 310.63934673888087 - t2 * 1131.0566563762241) +
          t3 * 1158.156643744946) +
         12.01430256224274;
  K[8] = ((L0 * 27.352840583774618 - t2 * 163.087005332458) +
          t3 * 169.61711046246791) +
         15.43485279396349;
  K[9] = ((L0 * 178.46354828640949 + t2 * 1344.7345030880281) -
          t3 * 2326.0074843466832) -
         4.376768753077438;
  K[10] = ((L0 * -4.4262517817914562 + t2 * 6.2624072580636261) -
           t3 * 5.8447903195292774) +
          2.1992758805544712;
  K[11] = ((L0 * -1.0331525139341911 + t2 * 138.52731466724981) -
           t3 * 209.6927380704991) -
          2.1909032218165052;
      //      }
        }
        
        
        
        
        
        
        
    }
}


/* Function Definitions */
/*
 * LEG_J_CAL
 *     J = LEG_J_CAL(PHI1,PHI4)
 *
 * Arguments    : float phi1
 *                float phi4
 *                float J[4]
 * Return Type  : void
 */
void leg_J_cal(float phi1, float phi4, float J[4])
{
	float t10;
  float t12;
  float t2;
  float t21;
  float t22;
  float t23;
  float t24;
  float t29;
  float t3;
  float t30;
  float t33;
  float t34;
  float t35;
  float t36;
  float t37;
  float t38;
  float t4;
  float t5;
  float t51;
  float t59;
  float t60;
  float t64;
  float t65;
  float t66;
  float t73;
  /* leg_J_2 */
  /*     J = leg_J_2(PHI1,PHI4) */
  /*     This function was generated by the Symbolic Math Toolbox version 25.1.
   */
  /*     2026-02-03 17:11:03 */
  t2 = cosf(phi1);
  t3 = cosf(phi4);
  t4 = sinf(phi1);
  t5 = sinf(phi4);
  t10 = t2 * 0.215;
  t12 = t4 * 0.215;
  t21 = t2 * 0.10965;
  t22 = t3 * 0.10965;
  t23 = t4 * 0.10965;
  t24 = t5 * 0.10965;
  t29 = t10 - t3 * 0.215;
  t30 = t12 - t5 * 0.215;
  t33 = t21 - t22;
  t34 = t23 - t24;
  t35 = t4 * t29 * 0.43;
  t36 = t5 * t29 * 0.43;
  t37 = t2 * t30 * 0.43;
  t38 = t3 * t30 * 0.43;
  t51 = t29 * t29 + t30 * t30;
  t59 = 1.0 / ((t22 - t21) + t51);
  t60 = t59 * t59;
  t64 = sqrtf((t33 * t33 + t34 * t34) - t51 * t51);
  t65 = 1.0 / t64;
  t66 = (t24 - t23) + t64;
  t73 = atanf(t59 * t66) * 2.0;
  t30 = cosf(t73);
  t64 = sinf(t73);
  t73 = 1.0 / (t60 * (t66 * t66) + 1.0);
  t23 = ((t23 + t37) - t35) * t60 * t66 +
        t59 * (t21 - t65 *
                         ((t2 * t34 * 0.2193 - t4 * t33 * 0.2193) +
                          t51 * (t35 - t37) * 2.0) /
                         2.0);
  t29 = ((t24 + t38) - t36) * t60 * t66 +
        t59 * (t22 - t65 *
                         ((t3 * t34 * 0.2193 - t5 * t33 * 0.2193) +
                          t51 * (t36 - t38) * 2.0) /
                         2.0);
  t4 = t10 + t30 * 0.255;
  t21 = t12 + t64 * 0.255;
  t66 = t30 * t73;
  t2 = t66 * t29;
  t64 *= t73;
  t51 = t64 * t29;
  t59 = t4 * t4;
  t60 = 1.0 / t4;
  t30 = t21 * t21 + t59;
  t65 = 1.0 / sqrtf(t30);
  t73 = 1.0 / t30;
  t66 = t10 - t66 * t23 * 0.51;
  t29 = t12 - t64 * t23 * 0.51;
  J[0] = t65 * (t21 * t66 * 2.0 - t4 * t29 * 2.0) / 2.0;
  t30 = t21 * (1.0 / t59);
  J[1] = t59 * t73 * (t60 * t66 + t30 * t29);
  J[2] = t65 * (t21 * t2 * 1.02 - t4 * t51 * 1.02) / 2.0;
  J[3] = -t59 * t73 * (t60 * (0.0 - t2 * 0.51) - t30 * (t51 * 0.51));
}




void VMC_Data_Get(Leg_State_t* Leg_State , float phi4, float dphi4, float phi1, float dphi1)//整合位置，速度，雅可比矩阵的求解
{
    Leg_State->last_dl0 = Leg_State->this_dl0;
    Leg_State->phi4 = phi4;
    Leg_State->phi1 = phi1;
    Leg_State->dphi4 = dphi4;
    Leg_State->dphi1 = dphi1;

    leg_pos(phi1,phi4,Leg_State->pos);
    Leg_State->l0 = Leg_State->pos[0];
    Leg_State->phi0 = Normalize_Angle_PI(Leg_State->pos[1]-1.57f);
    leg_spd(Leg_State->dphi1, Leg_State->dphi4, Leg_State->phi1, Leg_State->phi4, Leg_State->spd);
    Leg_State->dl0 = Leg_State->spd[0];
    Leg_State->this_dl0 = Leg_State->dl0;
    Leg_State->dphi0 = Leg_State->spd[1];
    Leg_State->ddl0 = (Leg_State->this_dl0 - Leg_State->last_dl0) / (TIME_STEP * 0.001);//可能要加低通滤波器

    leg_J_cal(phi1,phi4,Leg_State->J);
    for (int i = 0; i < 2; i++)
    {
        for (int j = 0; j < 2; j++)
        {
                Leg_State->j[j][i] = Leg_State->J[i * 2 + j];
        }
    }
}



float Get_Left_GasSpring_FN(float Left_Leglength)
{
    float Left_FN;
    Left_FN = 1.311e+07 * powf(Left_Leglength,6) - 1.8225e+07 * powf(Left_Leglength,5) + 1.0145e+07 * powf(Left_Leglength,4) -
    2.8776e+06 * powf(Left_Leglength,3) + 4.3630e+05 * powf(Left_Leglength,2) - 3.3513e+4*powf(Left_Leglength,1) + 955.5439;
    return Left_FN;
}




float Get_Right_GasSpring_FN(float Right_Leglength)
{
    float Right_FN;
    Right_FN = 3.6282e+06 * powf(Right_Leglength,6) - 2.7716e+06 * powf(Right_Leglength,5) + 9.5325e+04 * powf(Right_Leglength,4) +
    4.5222e+05 * powf(Right_Leglength,3) - 1.5418e+05 * powf(Right_Leglength,2) + 1.9290e+04*powf(Right_Leglength,1) -902.1393 ;
    return Right_FN;
}







