/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 23.2
 * C/C++ source code generated on  : 07-May-2024 03:40:01
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 23.2.
   */
  /*     2024-05-07 03:39:41 */
  t2 = L0 * L0;
  t3 = rt_powd_snf(L0, 3.0);
  K[0] = ((L0 * -276.35806235332961 + t2 * 430.85385014007989) -
          t3 * 310.80618685864391) +
         3.37505310248777;
  K[1] = ((L0 * 943.93710924215247 - t2 * 3247.03415053028) +
          t3 * 3412.3937418261949) -
         2.7302903758216721;
  K[2] = ((L0 * -31.018202689259311 + t2 * 9.4311847352673173) -
          t3 * 4.1067118988800564) +
         0.88355890794690417;
  K[3] = ((L0 * 143.89553134434561 - t2 * 436.4357909150491) +
          t3 * 437.301650935424) -
         0.64684803301872029;
  K[4] = ((L0 * -45.940678393479217 + t2 * 93.26295077773149) -
          t3 * 70.112297660288462) +
         0.8480005717245922;
  K[5] = ((L0 * 173.1394841583691 - t2 * 682.02757043811084) +
          t3 * 760.86662156901377) +
         3.0744649315333068;
  K[6] = ((L0 * -71.010221428434221 + t2 * 138.880303893591) -
          t3 * 104.39976138313089) +
         0.59066611754954668;
  K[7] = ((L0 * 261.69000640657492 - t2 * 1048.135047166993) +
          t3 * 1177.49523431479) +
         7.6585036499438779;
  K[8] = ((L0 * -63.844193336931568 - t2 * 63.539033047965212) +
          t3 * 160.63909375943811) +
         45.57941276352183;
  K[9] = ((L0 * 560.3068305401971 - t2 * 963.12788804908871) +
          t3 * 583.51441215527666) +
         34.954795946880779;
  K[10] = ((L0 * -9.9548429410864809 + t2 * 12.22559449264017) -
           t3 * 6.5835115426542261) +
          4.5557541301318931;
  K[11] = ((L0 * 14.133281630863481 + t2 * 16.492468813674439) -
           t3 * 48.813225038136792) +
          2.6675551639168908;
}

/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
